def formop(a,b,c,d,x,y):

  for widget in c.winfo_children():
    widget.destroy()
  
  c.geometry("600x600")
  c.title("Dashboard")
  c.configure(fg_color='white')
  # Configure grid layout for the window
  c.grid_columnconfigure((0,2), weight=0)
  c.grid_columnconfigure(1, weight=1)
  c.grid_rowconfigure((0,2), weight=0)
  c.grid_rowconfigure(1, weight=1)

  bm = a.CTkFrame(c,fg_color="whitesmoke",width=580,height=580)
  bm.grid(row=1,column=1,padx=5,pady=5,sticky="nsew")
  bm.grid_columnconfigure((0,1), weight=1)
  bm.grid_rowconfigure((0,1,2,3,4,5), weight=1)
  
  lab = a.CTkFrame(bm,fg_color="transparent")
  lab.grid(row=0,column=0,padx=5,pady=5,sticky="ew",columnspan = 2)
  lab.grid_rowconfigure((0,1),weight = 1)
  lab.grid_columnconfigure(0,weight = 1)
  custd = a.CTkLabel(lab,text="Enter Passanger Details",text_color="black",font=("Arial",14))
  custd.grid(row=0,column=0,padx=5,pady=5,sticky="w")
  cc = "ADD ADULT " + str(y)
  custcount = a.CTkLabel(lab,text=cc,text_color="black",font=("Arial",14))
  custcount.grid(row=1,column=0,padx=5,pady=2,sticky="w")
  nameframe = b.Labelframe(bm,text = "Enter name as per Aadhaar card/ Passport or any Govt. ID")
  nameframe.grid(row=1,column=0,padx=5,pady=5,sticky="ew")
  nameframe.grid_columnconfigure((0,1), weight=1)
  nameframe.grid_rowconfigure((0,1,2), weight=1)
  gensub = a.CTkFrame(nameframe,fg_color="transparent")
  gensub.grid(row=0,column=0,padx=5,pady=5,sticky="nsew")
  gensub.grid_columnconfigure((0,1,3), weight=1)
  gensub.grid_rowconfigure(0, weight=1)
  gen1 = a.CTkRadioButton(gensub,text="Mr",text_color = "black",value="Mr")
  gen1.grid(row=0,column=0,padx=5,pady=5)
  gen2 = a.CTkRadioButton(gensub,text="Ms",text_color = "black",value="Mr")
  gen2.grid(row=0,column=1,padx=5,pady=5)
  gen3 = a.CTkRadioButton(gensub,text="Mrs",text_color = "black",value="Mr")
  gen3.grid(row=0,column=2,padx=5,pady=5)
  first = b.Entry(nameframe,style = "primary")
  first.grid(row=1,column=0,padx=5,pady=5,sticky="ew")
  last = b.Entry(nameframe,style = "primary")
  last.grid(row=1,column=1,padx=5,pady=5,sticky="ew")

  contframe = a.CTkFrame(bm,fg_color="transparent")
  contframe.grid(row=2,column=0,padx=5,pady=5,sticky="ew")
  contframe.grid_columnconfigure((0,1), weight=1)
  contframe.grid_rowconfigure((0,1), weight=1)
  cont = a.CTkLabel(contframe,text="Contact Details",text_color="black",font=("Arial",14))
  cont.grid(row=0,column=0,padx=5,pady=5,sticky="ew")
  ph = b.Entry(contframe,style = "primary")
  ph.grid(row=1,column=0,padx=5,pady=5,sticky="ew")
  email = b.Entry(contframe,style = "primary")
  email.grid(row=1,column=1,padx=5,pady=5,sticky="ew")