def formop(a,b,c,d,x,y):

  ct = a.CTkToplevel(c, fg_color="white")
  ct.geometry("600x600")
  ct.title("Dashboard")
  ct.configure(fg_color='white')
    # Configure grid layout for the window
  ct.grid_columnconfigure((0,2), weight=0)
  ct.grid_columnconfigure(1, weight=1)
  ct.grid_rowconfigure((0,2), weight=0)
  ct.grid_rowconfigure(1, weight=1)
  def on_entry_click(event, entry, placeholder):
      if entry.get() == placeholder:
          entry.delete(0, a.END)
          entry.configure(foreground="black")

  def on_focus_out(event, entry, placeholder):
      if entry.get() == "":
          entry.insert(0, placeholder)
          entry.configure(foreground="grey")
  
  def on_radio_button_change():
      selected_value = radio_var.get()
      print(f"Selected option: {selected_value}")

  radio_var = a.StringVar()
  bm = a.CTkFrame(ct,fg_color="white",width=580,height=580,border_color="black",border_width=1)
  bm.grid(row=1,column=1,padx=5,pady=5,sticky="nsew")
  bm.grid_columnconfigure((0,1), weight=1)
  bm.grid_rowconfigure((0,1,2,3,4,5), weight=1)
  
  lab = a.CTkFrame(bm,fg_color="transparent")
  lab.grid(row=0,column=0,padx=5,pady=5,sticky="ew",columnspan = 2)
  lab.grid_rowconfigure((0,1,2),weight = 1)
  lab.grid_columnconfigure(0,weight = 1)
  custd = a.CTkLabel(lab,text="Enter Passanger Details",text_color="black",font=("Arial",14))
  custd.grid(row=0,column=0,padx=5,pady=0,sticky="w")
  cc = "ADD ADULT " + str(y)
  custcount = a.CTkLabel(lab,text=cc,text_color="black",font=("Arial",14))
  custcount.grid(row=1,column=0,padx=5,pady=2,sticky="w")
  nameframe = b.Labelframe(bm,text = "Enter name as per Aadhaar card/ Passport or any Govt. ID")
  nameframe.grid(row=1,column=0,padx=5,pady=2,sticky="ew")
  nameframe.grid_columnconfigure((0,1), weight=1)
  nameframe.grid_rowconfigure((0,1,2), weight=1)
  gensub = a.CTkFrame(nameframe,fg_color="transparent")
  gensub.grid(row=0,column=0,padx=5,pady=5,sticky="nsew")
  gensub.grid_columnconfigure((0,1,3), weight=1)
  gensub.grid_rowconfigure(0, weight=1)
  gen1 = a.CTkRadioButton(gensub,text="Mr",text_color = "black",value="Mr",variable = radio_var,command=on_radio_button_change)
  gen1.grid(row=0,column=0,padx=5,pady=5)
  gen2 = a.CTkRadioButton(gensub,text="Ms",text_color = "black",value="Ms",variable = radio_var,command=on_radio_button_change)
  gen2.grid(row=0,column=1,padx=5,pady=5)
  gen3 = a.CTkRadioButton(gensub,text="Mrs",text_color = "black",value="Mrs",variable = radio_var,command=on_radio_button_change)
  gen3.grid(row=0,column=2,padx=5,pady=5)
  first = b.Entry(nameframe,style = "primary")
  first.grid(row=1,column=0,padx=5,pady=5,sticky="ew")
  first.insert(0, "First Name")
  first.bind("<FocusIn>", lambda event: on_entry_click(event, first, "First Name"))
  first.bind("<FocusOut>", lambda event: on_focus_out(event, first, "First Name"))
  last = b.Entry(nameframe,style = "primary")
  last.grid(row=1,column=1,padx=5,pady=5,sticky="ew")
  last.insert(0, "Last Name")
  last.bind("<FocusIn>", lambda event: on_entry_click(event, last, "Last Name"))
  last.bind("<FocusOut>", lambda event: on_focus_out(event, last, "Last Name"))

  contframe = b.LabelFrame(bm,text = "")
  contframe.grid(row=3,column=0,padx=5,pady=2,sticky="")
  contframe.grid_columnconfigure((0,1), weight=1)
  contframe.grid_rowconfigure((0,1,2), weight=1)
  cont = a.CTkLabel(bm,text="Contact Details",text_color="black",font=("Arial",14))
  cont.grid(row=2,column=0,padx=5,pady=5,sticky="w")
  ph = b.Entry(contframe,style = "primary")
  ph.grid(row=1,column=0,padx=5,pady=5,sticky="")
  ph.insert(0, "Phone Number")
  ph.bind("<FocusIn>", lambda event: on_entry_click(event, ph, "Phone Number"))
  ph.bind("<FocusOut>", lambda event: on_focus_out(event, ph, "Phone Number"))
  email = b.Entry(contframe,style = "primary")
  email.grid(row=1,column=1,padx=5,pady=5,sticky="ew")
  email.insert(0, "Email ID eg: user@gmail.com")
  email.bind("<FocusIn>", lambda event: on_entry_click(event,email, "Email ID eg: user@gmail.com"))
  email.bind("<FocusOut>", lambda event: on_focus_out(event, email, "Email ID eg: user@gmail.com"))
  booking = b.Button(contframe,text="Book Flight",command ="",style = "primary")
  booking.grid(row=2,column=1,padx=5,pady=5,sticky="e")

  